### ISSUE TITLE
Profile Photo: Not gravatar 

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#44] opened 2015-03-25 17:20 UTC
We haven't discussed it for awhile but just to voice an opinion: I feel it would be better to have the profile pic integrated into the system instead of going out to Gravatar. Although it's popular, I think most people don't have it setup and it would feel more streamlined to have an embed "Upload Profile Pic" interface…

**Comment by jamiewilson** [comment] 2015-03-25 17:28
Yea, I totally agree. I've looking into it a bit, but it's quite a bit more complex than you'd think. The package I'm using for avatars plans on supporting this in the future, so it might make more sense to let that guy to the work. But I have no idea how long that might take:

https://github.com/bengott/meteor-avatar/issues/9

This could be a good stopgap if I can get it integrated: https://www.filepicker.com/

Duplicate of #24

**Comment by jamiewilson** [comment] 2015-06-26 14:50
This issue was moved to weld-co/welderwire-theme#21

**Closed by jamiewilson** 2015-06-26 14:50 UTC
Labels: duplicate, enhancement
